### PR TITLE
Roman Numeral Converter

### PR DESCRIPTION
**Pull request by BrianLoughnane**
- Flesh out spec based on roman numeral rules (http://mathforum.org/dr.math/faq/faq.roman.html)
- implement solution to get full spec passing

### CODE REVIEW

**Comment by BrianLoughnane** [comment]
Really enjoyed the frontend masters course :+1:

**Comment by searls** [comment]
Hey @BrianLoughnane -- thanks a lot for doing the exercise and showing your solution. I'm going to leave the codebase as-is (the oversimplification it represents is helpful to me when I teach out of the repo), but looks like you really wrote a robust one!

**Comment by BrianLoughnane** [comment]
It's totally fine, I was going through the video and did all that stuff anyway, just figured I'd float over a pull request.

**Comment by searls** [comment]
Thanks a lot for sharing. It encouraged me today

**Comment by BrianLoughnane** [comment]
To tweet this? https://twitter.com/searls/status/719726285803675648 =P

**Comment by searls** [comment]
Lol, nope, that subtweet wasn't directed at you. It was all @deanius's fault https://github.com/testdouble/scripty/pull/6 :green_heart: :green_heart: :green_heart: :green_heart:

**Pull request closed without merging**
